service: community-graph

frameworkVersion: ">=1.2.0 <2.0.0"

custom:
  stage: "${opt:stage, self:provider.stage}"

provider:
  name: aws
  runtime: python3.6
  environment: ${file(env.yml):${self:custom.stage}}

plugins:
  - serverless-python-requirements

functions:
  page-summary:
      name: CommunityGraphGeneratePageSummary-${self:provider.environment.TITLE}
      handler: handler.generate_page_summary
      events:
        - schedule: rate(1 hour)
  twitter-import:
      name: CommunityGraphTwitterImport-${self:provider.environment.TITLE}
      handler: handler.twitter_import
      events:
        - schedule: rate(1 hour)
  twitter-clean-links:
      name: CommunityGraphTwitterCleanLinks-${self:provider.environment.TITLE}
      handler: handler.twitter_clean_links
      events:
        - schedule: rate(1 hour)
  twitter-hydrate-links:
      name: CommunityGraphTwitterHydrateLinks-${self:provider.environment.TITLE}
      handler: handler.twitter_hydrate_links
      events:
        - schedule: rate(1 hour)
  github-import:
      name: CommunityGraphGitHubImport-${self:provider.environment.TITLE}
      handler: handler.github_import
      events:
        - schedule: rate(1 hour)